---
- name: Configure RHEL 9 VSI on IBM Cloud
  hosts: all
  become: yes

  tasks:
    - name: Update all packages
      dnf:
        name: "*"
        state: latest

    - name: Install basic utilities
      dnf:
        name:
          - vim
          - git
          - curl
        state: present
